import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { FileError } from '@/domain/errors';
import { detectBuildDirectories, detectByHeuristic } from './detect-build-dirs';

describe('detect-build-dirs', () => {
  const testDir = './test-detect-dirs';

  beforeEach(async () => {
    await mkdir(testDir, { recursive: true });
  });

  afterEach(async () => {
    await rm(testDir, { recursive: true, force: true });
  });

  describe('detectBuildDirectories', () => {
    test('detects outDir from tsconfig.json', async () => {
      await writeFile(
        `${testDir}/tsconfig.json`,
        JSON.stringify({
          compilerOptions: {
            outDir: 'custom-dist',
          },
        }),
      );

      const detected = detectBuildDirectories(testDir).found;
      expect(detected).toContain('custom-dist');
    });

    test('detects --outDir from package.json scripts', async () => {
      await writeFile(
        `${testDir}/package.json`,
        JSON.stringify({
          scripts: {
            build: 'tsc --outDir build-output',
          },
        }),
      );

      const detected = detectBuildDirectories(testDir).found;
      expect(detected).toContain('build-output');
    });

    test('reads outDir from a tsconfig with comments and trailing commas', async () => {
      await writeFile(`${testDir}/tsconfig.json`, '{\n  // generated by tsc --init\n  "compilerOptions": { "outDir": "lib", },\n}\n');
      expect(detectBuildDirectories(testDir).found).toContain('lib');
    });

    test('ignores an empty tsconfig outDir instead of excluding everything', async () => {
      await writeFile(`${testDir}/tsconfig.json`, JSON.stringify({ compilerOptions: { outDir: '' } }));
      expect(detectBuildDirectories(testDir).found).toEqual([]);
    });

    test('missing files are not a problem', async () => {
      expect(detectBuildDirectories(testDir)).toEqual({ found: [], skipped: [] });
    });

    test('reports an unparseable tsconfig.json', async () => {
      await writeFile(`${testDir}/tsconfig.json`, '{ invalid json }');
      const { found, skipped } = detectBuildDirectories(testDir);
      expect(found).toEqual([]);
      expect(skipped.map(FileError.$is('ParseFailed'))).toEqual([true]);
    });
  });

  describe('detectByHeuristic', () => {
    test('detects directories with build-like suffixes', async () => {
      await mkdir(`${testDir}/storybook-static`);
      await mkdir(`${testDir}/my-app-dist`);
      await mkdir(`${testDir}/random-dir`);

      const detected = detectByHeuristic(testDir).found;
      expect(detected).toContain('storybook-static');
      expect(detected).toContain('my-app-dist');
      expect(detected).not.toContain('random-dir');
    });

    test('ignores files with build-like suffixes', async () => {
      await writeFile(`${testDir}/file-static`, 'content');
      const detected = detectByHeuristic(testDir).found;
      expect(detected).toEqual([]);
    });
  });
});
